inherit_gem:
  standard: config/base.yml

require:
- rubocop-rails
- standard

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
  - "db/schema.rb"
  - "vendor/**/*"

Style/StringLiterals:
  Exclude:
  # ruby.ci appends a few helper gems to the bottom of the Gemfile which we don't care to lint
  - "Gemfile"
