inherit_gem:
  standard: config/base.yml
  standard-rails: config/base.yml

require:
- rubocop-rails
- standard
- standard-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
  - "db/schema.rb"
  - "vendor/**/*"
