inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
Layout/LineLength:
  Exclude:
    - 'Gemfile'
Style/ClassAndModuleChildren:
  Enabled: false
