# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at https://docs.scoutapm.com#environment-variables for more information.
common: &defaults
  name: Conduit
  key: <%= ENV['SCOUT_KEY'] %>
  monitor: true
  errors_enabled: true
  auto_instruments: true
  # log_level: info

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults

